###
 # config/activegateway/activegateway.web.yml
 # 
 # dsnは配列形式で複数記述する事によって、ランダムでどちらか一方を使用するようになります。
 # 
 # <example>
 #     alias :
 #         dsn  : '[driver]://[user]:[password]@[host]/[dbname]'
 #         conf : '/path/to/samurai/config/activegateway/conf/alias.yml'
 # </example>
 #/
base:
    dsn : 'mysql://samurai:Cj9bJWN4WZ2U@192.168.200.1/samurai'

sandbox:
    dsn : 'mysql://befool.sandbox:sandman@192.168.200.1/sandbox'
